#Final Project
INFO 3900

```{r}
#|label: import-setup

library(tidyverse)
library(MatchIt)

```
## The Data

```{r}

load("data/poli1.Rdata")

head(poli)

```
The data is sourced from TKTKTK. It contains synthetic data to emulate the responsiveness of a politician to the messages of their constituents.

## Data Question

Treatment: Proximity of constituent

Outcome: Whether or not the legislator responds to the constituent’s request

## Matching

We attempt to match.

```{r}
#|label: matching

treatment <- poli$treat_out
outcome <- poli$code_some_response_given

# Step 1
match <- matchit(treat_out ~ code_some_response_given + leg_party + medianhhincom,
                 data = poli,
                 method = "nearest",
                 distance = "logit",
                 estimand = "ATT",
                 ratio = 1,
                 replace = T)

match.data(match) -> matched_df

lm_mod <- lm(code_some_response_given ~ treat_out + leg_party + medianhhincom,
             data = matched_df)

summary(lm_mod)


att_est <- coef(lm_mod)["treat_out"]
print(att_est)

summary(match)$nn # number of matched

print(round(att_est, 2)) # causal estimate

```


